config/routes.rb
Rails.application.routes.draw do
  get 'comments/index'
  resources :users do
    resources :posts
  end

  resources :categories do
    resources :posts
  end

  resources :posts do
    resources :comments
  end

  root 'home#index'
    get 'signup', to: 'users#new'
    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true
  validates :content, presence: true
  belongs_to :user
  belongs_to :category
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, uniqueness: true, length: { minimum: 3 }
  validates :email, presence: true, uniqueness: true
  has_secure_password
  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      redirect_to root_path
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @category = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comments = Comment.all
  end

  def new
    @post = Post.find(params[:post_id])
    @comment = Comment.new
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    @comment.post_id = @post.id
    if @comment.save
      redirect_to post_path(@post)
    else
      render 'new'
    end
  end

  def show
    @comment = Comment.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy

    redirect_to post_path(@post)
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :post_id, :user_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update]

  def index
    @posts = Post.all
    @posts = Post.order(params[:sort])
  end

  def new
    @post = Post.new
    if params[:category_id]
      @category = Category.find(params[:category_id])
    else
      @category = Category.first
    end
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      flash[:message] = "#{@post.title} has been created successfully!"
      redirect_to post_path(@post)
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def edit
  end

  def update
    if @post.update(post_params)
      flash[:message] = "#{@post.name} has been updated successfully!"
      redirect_to post_path(@post)
    else
      render 'edit'
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :description, :content, :category_id)
  end

  def set_post
    @post = Post.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.find_by(username: params[:user][:username])
    if @user && @user.authenticate(params[:user][:password])
      session[:user_id] = @user.id
      flash[:message] = "Welcome Back to AZ Blog, #{@user.username}!"
      redirect_to user_path(@user)
    else
      flash[:message] = "The username or password that you entered is incorrect."
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:message] = "#{@user.username} created successfully!"
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @user.update(user_info_params)
      flash[:message] = "#{@user.username} updated successfully!"
      redirect_to user_path(@user)
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def user_info_params
    params.require(:user).permit(:username, :email, :password, :bio, :interests, :location)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar_url(user)
      gravatar_id = Digest::MD5::hexdigest(user.username).downcase
      "http://gravatar.com/avatar/#{gravatar_id}.png?s=64"
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/index.html.erb
<div class="categories">
  <h2>Inside the Writers Corner</h2>
</div>

<table class="all-categories" align="center" width="60%">
    <tr>
      <th>Category</th>
      <th>Posts</th>
      <th>Latest Post</th>
    </tr>
    <% @category.each do |category| %>
      <tr>
        <td><h3><i class="fas fa-book"></i> <%= link_to category.name, category %></h3><%= category.description %></td>
        <td><%= category.posts.count %></td>
        <% category.posts.each do |post| %>
            <td><%= link_to post.title, post %></td>
          <% end %>
      </tr>
    <% end %>
</table>

app/views/categories/show.html.erb
<div class="categories-show">
<h1> <%= @category.name %> </h1>
<table class="category-post" align="center" width="60%">
    <th>Post</th>
    <th>Created By</th>
    <th>Published On</th>
  <% @category.posts.each do |post| %>
    <tr>
      <td><p><%= link_to post.title, post %></p></td>
      <td><p><%= post.user.username %></p></td>
      <td><p><%= post.created_at.strftime("%B %d, %Y") %></p></td>
    </tr>
  <% end %>
</table>
</div>

app/views/comments/_form.html.erb
<%= form_for [@post, @comment] do |f| %>
  <p><%= f.label "Comment" %><br><br><%= f.text_area :body, :class => 'post-control' %></p>
  <%= f.submit "Submit", :class => 'submit-button' %>
<% end %>

app/views/comments/index.html.erb
<h1>Comments</h1>
<% @comments.each do |comment| %>
  <%= comment.body %>
<% end %>

app/views/comments/new.html.erb
<div class="create-comment">
  <h2>Create Comment</h2>
  <%= render 'form' %>
</div>

app/views/home/index.html.erb
<div class="homepage">
  <h1 class="tagline">Connect with Writers and Content Creators</h1>
  <%= image_tag("typewriter.jpg", :class => "home_image") %>
</div>

app/views/layouts/_navigation.html.erb
<div class="navbar" id="myNavMenu">
    <%= link_to root_path do %>
      <i class="fa fa-paragraph fa-2x"></i>
      <%= content_tag :span, "AZ.blog", :class => "home" %>
    <% end %>

    <%= link_to "Users", users_path %>
    <%= link_to "Posts", posts_path %>
    <%= link_to "Categories", categories_path %>
  <% if logged_in? %>
    <%= link_to "Create Post", new_post_path %>
    <%= link_to "Profile", user_path(current_user) %>
    <%= link_to "Logout", logout_path, method: :delete %>
  <% else %>
    <%= link_to "Join", signup_path %>
    <%= link_to "Login", login_path %>
  <% end %>
  <a href="javascript:void(0);" class="icon" onclick="responsiveMenu()">
    <i class="fa fa-bars" style="font-size:24px"></i>
  </a>
</div>

<script>
  function responsiveMenu() {
  let x = document.getElementById("myNavMenu");
    if (x.className === "navbar") {
      x.className += " responsive";
  } else {
      x.className = "navbar";
    }
  }
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AZ-Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_include_tag 'https://kit.fontawesome.com/a076d05399.js' %>
    <%= stylesheet_link_tag    'application', 'https://fonts.googleapis.com/css?family=Open+Sans|Montserrat:900&display=swap', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

    <div class="message">
      <% if flash[:message] %>
        <p><%= flash[:message] %></p>
      <% end %>
    </div>

    <%= render 'layouts/navigation' %>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for [@user, @post] do |f| %>
  <p><%= f.label :title %><br><br><%= f.text_field :title, :class => 'post-control' %></p>
  <p><%= f.label :category_id %><br><br><%= f.collection_select :category_id, Category.all, :id, :name, { include_blank: false}, { class: "form-control" } %></p>
  <p><%= f.label :description %><br><br><%= f.text_field :description, :class => 'post-control' %></p>
  <p><%= f.label :content %><br><br><%= f.text_area :content, :class => 'form-area' %></p>
  <%= f.submit :class => 'submit-button' %>
<% end %>

app/views/posts/edit.html.erb
<h2>Edit Post</h2>
<%= render 'form' %>

app/views/posts/index.html.erb
<div class="posts-index">
<h1>All Blog Posts</h1>
<%= image_tag("Blog.jpg", :class => "posts_image") %>
<table class="all-posts" id="all-posts" align="center" width="60%">
  <tr>
    <th><h3><%= link_to "Post Title", :sort => "title" %></h3></th>
    <th><h3><%= link_to "Author", :sort => "user_id" %></h3></th>
    <th><h3><%= link_to "Publish Date", :sort => "created_at" %></h3></th>
  </tr>
  <% @posts.each do |post| %>
  <tr>
    <td><%= link_to post.title, post %></td>
    <td><%= link_to post.user.username, post.user %></td>
    <td><%= post.created_at.strftime("%B %d, %Y") %></td>
  </tr>
  <% end %>
</table>
</div>

app/views/posts/new.html.erb
<div class="create-post">
  <h2>Create a Post</h2>
  <%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div class="post-container">
  <h1><%= @post.title %></h1>
  <h3><%= @post.description %></h3>
  <p>By <%= @post.user.username %> | <%= @post.created_at.strftime("%B %d, %Y") %></p>
  <p><%= @post.content %></p>

<% if logged_in? %>
  <%= link_to 'Add Comment', new_post_comment_path(@post), :class => 'submit-button' %>

  <% if @post.user == current_user  %>
    <%= link_to 'Edit Post', edit_post_path(@post), :class => 'submit-button' %>
  <% end %>

  <br><br>
    <% @post.comments.each do |comment| %>
      <%= comment.user.username %> commented <%= comment.body %> on
      <%= comment.created_at.strftime("%B %d, %Y") %>
      <% if comment.user == current_user %>
      <%= link_to 'Delete Comment', post_comment_path(@post, comment), :class => 'submit-button', method: :delete, data: { confirm: 'Are you sure?'} %>
      <% end %>
    <% end %>
  <% else %>
  <h4><%= link_to "Login", login_path %> to see comments</h4>
<% end %>
</div>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <p><%= f.label :username %><br><%= f.text_field :username, :class => 'form-control' %></p>
  <p><%= f.label :email %><br><%= f.email_field :email, :class => 'form-control' %></p>
  <p><%= f.label :password %><br><%= f.password_field :password, :class => 'form-control' %></p>
  <%= f.submit :class => 'submit-button' %>

  <% if !logged_in? %>
    <p>Already have an account? <%= link_to "Log In", login_path, :class => 'links' %></p>
  <% end %>
  
  <div class="message">
    <% if @user.errors.any? %>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    <% end %>
  </div>

<% end %>

<% if current_user %>

<h2>Profile Info</h2>
  <%= form_for @user do |f| %>
    <p><%= f.label :bio %><br><%= f.text_field :bio, :class => 'form-control' %></p>
    <p><%= f.label :interests %><br><%= f.text_field :interests, :class => 'form-control' %></p>
    <p><%= f.label :location %><br><%= f.text_field :location, :class => 'form-control' %></p>
    <%= f.submit "Update Info", :class => 'submit-button' %>
  <% end %>
<% end %>

app/views/users/edit.html.erb
<div class="create-user">
  <h2>Profile Settings</h2>
  <%= render 'form' %>
</div>

app/views/users/index.html.erb
<div class="all-users">
  <h1>AZ Blog Users</h1>
  <table id="users-list" align="center" width="60%">
    <tr>
      <th><h3>Username</h3></th>
      <th><h3>Posts</h3></th>
      <th><h3>Joined</h3></th>
    </tr>
  <% @users.each do |user| %>
    <tr>
      <td><%= link_to user.username, user %></td>
      <td><%= user.posts.count %></td>
      <td><%= user.created_at.strftime("%B %d, %Y") %></td>
    </tr>
  <% end %>
</table>
</div>

app/views/users/new.html.erb
<div class="create-user">
  <h1>Join AZ Blog</h1>
  <%= render 'form' %>
</div>

app/views/users/show.html.erb
<div class="user-profile">

  <%= image_tag avatar_url(@user) %>
  <h1><%= @user.username %></h1>
  <h3><%= @user.posts.count %> Posts</h3>

  <div class="user-info">
    <h4>Started Blogging: <%= @user.created_at.strftime("%B %d, %Y") %></h4>
    <h4><%= @user.bio %></h4>
    <h4>Based in <%= @user.location %></h4>
    <h4>Interests: <%= @user.interests %></h4>
  </div>

  <% if logged_in? && @user.id == current_user.id %>
    <br>
    <%= link_to 'Edit Profile', edit_user_path(@user), :class => 'submit-button' %>
  <% end %>
  <div class="user-posts">
    <h3><%= @user.username %>'s Posts</h3>
      <% @user.posts.each do |post| %>
        <h4 class="user-posts-list"><%= link_to post.title, post_path(post) %></h4>
      <% end %>
  </div>
</div>